version: '3.3'
services:
  # Usado quando se quer testar um backup do integratto
  db_integratto2:
    image: postgres:15-bullseye

    ports:
      - "5454:5432"
    restart: always
    volumes:
      - $PWD/database/ERP/:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "LANGUAGE=pt_BR.UTF-8"






