CREATE DATABASE integratto2
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    TEMPLATE = template0
    CONNECTION LIMIT = -1;

ALTER DATABASE integratto2 SET client_encoding TO 'WIN1252';

ALTER DATABASE integratto2 set DATESTYLE='iso, dmy';

CREATE ROLE group_nasajon
  NOSUPERUSER INHERIT NOCREATEDB CREATEROLE NOREPLICATION;


CREATE ROLE integratto2_mestre LOGIN
  ENCRYPTED PASSWORD 'md5785a65fd7fca52fcff0fac3bbf13f73d'
  NOSUPERUSER INHERIT NOCREATEDB CREATEROLE NOREPLICATION;
GRANT group_nasajon TO integratto2_mestre;


CREATE ROLE nsj_integratto_admin LOGIN
  ENCRYPTED PASSWORD 'md5c5455f79ca3605c4286e3285e7f688eb'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT group_nasajon TO nsj_integratto_admin;
